### ISSUE TITLE
cache for frequency computation

### ISSUE THREAD

**Issue by mcfrank** [smeylan/childes-db#13]
need to cache total word tokens per speaker per transcript or else we can't compute proportions without loading ALL tokens/utterances

this could be a good table to cache somewhere, not sure how to implement though.

**Comment by mcfrank** [comment]
more thoughts: 

`transcript_by_speaker` should cache all the computed variables:
* number of utterances
* mlu
* ttr
* number of types and tokens
* number of turns

all of this will make things go much faster on the shiny apps end.

**Comment by amsan7** [comment]
to clarify, 1 turn = consecutive utterances by a speaker?

**Comment by mcfrank** [comment]
sorry, unclear issue. let's have 

* number of utterances
* mean utterance length (mean of length)
* number of types
* number of tokens

and call it a day for now.

**Comment by amsan7** [comment]
ok, i created a table called transcript_by_speaker - want to take a look?
