### ISSUE TITLE
extract basic utterance terminators: period, question mark, and exclamation mark  

### ISSUE THREAD

**Issue by kemacdonald** [smeylan/childes-db#15]
this is useful for separating questions from declaratives, which I think is a common use case. see section 9.6 (pgs. 60-61) of the [CHAT manual](http://talkbank.org/manuals/CHAT.pdf) for more info. 

could add this info to the utterance and token tables?

**Comment by amsan7** [comment]
yes, we can add columns to both tables. i'm unsure about the naming - `utterance_terminator` for token and `terminator` for utterance? with the values being "?", "!", ".", etc? i like to stick with what CHILDES calls these terms and don't like prepending table names to columns in that table, but let me know what you think.

**Comment by amsan7** [comment]
More thoughts: a limitation of just calling the column `utterance_type` with values *declarative*, *interrogative*, etc is the ambiguity in *!*-terminated utterances, according to CHILDES: 

> An exclamation point marks the end of an imperative or emphatic utterance.

But maybe we just call any utterance that ends with *!* as *exclamatory* / *emphatic*. This may be misleading but the sentence types are more intuitive as a search parameter than the individual markers

**Comment by kemacdonald** [comment]
great! the column naming conventions you proposed seem reasonable to me. but i do agree that from the user's perspective, querying the sentence types feels more intuitive. what about creating the `utterance_type` column and staying close to the CHAT labels. something like: 

- period -> _declarative_ 
- question mark -> _question_
- exclamation mark -> _imperative_emphatic_

and then we can add a warning/note about the ambiguity of the imperative_emphatic utterance type to the vignette

**Comment by amsan7** [comment]
FYI there are apparently "special utterance terminators" as detailed in section 9.11 (e.g. interruption, trailing off, etc). I'm just going to keep whatever is in the XML (names seem reasonable so far)

**Comment by amsan7** [comment]
in `utterance` and `token` table under column `type`
