### ISSUE TITLE
schema updates

### ISSUE THREAD

**Issue by smeylan** [smeylan/childes-db#20]
- [x] utterance.order should be named utterance.utterance_order to clarify relationship to token.token_order
- [x] Add the dependent tiers
- [x]  Transcript should have ` target_child_sex` for consistency with utterance and token tables
- [ ]  `participant` table could be renamed the `speaker` table. This clarifies the relationship to fields like `speaker_code`, `speaker_name`, etc.
- [ ] we could remove all speaker fields, because these can all be accessed through a single join using the speaker_id field
- [ ]  we could similarly remove target_child{age, name, sex} because these can be accessed through a join on the target_child_id

**Comment by amsan7** [comment]
3 - maybe it should be the reverse? CHILDES uses the term "participant"
4/5 - i think some benefits to denormalization are the improvements to speed and simplification of queries

**Comment by amsan7** [comment]
i think `speaker` is better than `participant` i just wonder if there's a reason CHILDES did it this way. maybe not all participants are speakers? regardless `speaker` is a lot clearer than `participant` and probably makes sense for the majority of cases...
